AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template for The BB Cousins HVAC Website.
  Static website hosted on S3, delivered via CloudFront (with OAC), 
  secured with existing ACM cert, and routed through Route 53.

Parameters:
  DomainName: #This is the root domain, e.g. example.com
    Type: AWS::SSM::Parameter::Value<String> #I store the domain name in SSM Parameter Store
    Default: /hvac/website/domainName
    Description: Root domain name 

  BucketName: # S3 bucket name for static website
    Type: AWS::SSM::Parameter::Value<String> #I store the bucket name in SSM Parameter Store
    Default: hvacwebsitebucket
    Description: SSM parameter storing the private S3 bucket name

  CertificateArn: # ARN of existing ACM certificate in us-east-1
    Type: AWS::SSM::Parameter::Value<String> #I store the cert ARN in SSM Parameter Store
    Default: /hvac/website/certificateArn
    Description: ARN of the existing ACM certificate 

Resources:

  # S3 Bucket for static website
  HVACWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration: # Block all public access
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration: # Enable versioning
        Status: Enabled

  # CloudFront Origin Access Control (OAC)
  HVACWebsiteOAC: # New OAC for CloudFront to access S3 bucket
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: HVACWebsiteOAC
        Description: OAC for HVAC Website S3 bucket
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # Bucket Policy for OAC
  HVACWebsiteBucketPolicy: # This policy allows CloudFront OAC to access the S3 bucket
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref HVACWebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${HVACWebsiteBucket.Arn}/*" # Allow access to all objects in the bucket
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${HVACWebsiteCloudFront}" # Restrict to this CloudFront distribution

  # CloudFront Distribution
  HVACWebsiteCloudFront: # CloudFront distribution for the website
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html #this is a static website
        Aliases:
          - !Ref DomainName   # only root domain
        Origins:
          - Id: s3Origin
            DomainName: !GetAtt HVACWebsiteBucket.RegionalDomainName # Use RegionalDomainName for better performance
            S3OriginConfig: {}
            OriginAccessControlId: !Ref HVACWebsiteOAC #i reference the OAC here
        DefaultCacheBehavior:
          TargetOriginId: s3Origin
          ViewerProtocolPolicy: redirect-to-https # to make sure all traffic is HTTPS
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate: # this is where I attach the existing ACM cert by referencing the parameter here.
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

  # Route 53 - root domain record
  HVACWebsiteRootRecord: # I create an A record for the root domain pointing to CloudFront
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${DomainName}." # this assumes the hosted zone is named the same as the domain
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt HVACWebsiteCloudFront.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # fixed CloudFront zone ID

Outputs:
  WebsiteBucketName: # Output the S3 bucket name
    Description: Private S3 bucket hosting website files
    Value: !Ref HVACWebsiteBucket

  CloudFrontURL: # Output the CloudFront distribution URL
    Description: CloudFront distribution URL
    Value: !GetAtt HVACWebsiteCloudFront.DomainName

  WebsiteDomain: # Output the custom domain name
    Description: Custom domain for the HVAC website
    Value: !Ref DomainName

  ACMCertificateArn: # Output the ACM certificate ARN
    Description: ARN of the ACM certificate
    Value: !Ref CertificateArn

  CloudFrontDistributionId: # Output the CloudFront distribution ID
    Description: CloudFront distribution ID
    Value: !Ref HVACWebsiteCloudFront
